
call pathogen#infect()
call pathogen#helptags()



"autocmd BufRead,BufEnter,BufNewFile *.arc so /home/mds/projects/arc/arc2/vimarc.vim
autocmd BufRead,BufEnter,BufNewFile *.arc set lisp ft=lisp
autocmd BufRead,BufEnter,BufNewFile *.txt set wrap syntax=on textwidth=72 formatoptions=l  filetype=textile

filetype plugin indent on


set expandtab
set tabstop=4
set shiftwidth=4
set cindent
set autoindent
set smarttab
"set expandtab
 

set guioptions=-m

set guifont=Menlo\ Regular:h14"

set incsearch
set ignorecase
set smartcase
set scrolloff=4

syntax on
"syntax enable


"map j gj
"map k gk
"map $ g$
"map ^ g^
"color slate

"color xoria256 

filetype on  " Automatically detect file types.
set nocompatible  
 
" Add recently accessed projects menu (project plugin)
set viminfo^=!
 
" Minibuffer Explorer Settings
"let g:miniBufExplMapWindowNavVim = 1
"let g:miniBufExplMapWindowNavArrows = 1
"let g:miniBufExplMapCTabSwitchBufs = 1
"let g:miniBufExplModSelTarget = 1
 
" alt+n or alt+p to navigate between entries in QuickFix
"map <silent> <m-p> :cp <cr>
"map <silent> <m-n> :cn <cr>
 
 

set formatoptions=tcqr1


" Visual
set showmatch  " Show matching brackets.
set mat=5  " Bracket blinking.

" gvim specific
set mousehide  " Hide mouse after chars typed
set mouse=a  " Mouse in all modes

" Backups & Files
set backup                     " Enable creation of backup file.
set backupdir=~/tmp " Where backups will go.
set directory=~/tmp     " Where temporary files will go.



set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo
set wildignore=*.swp,*.bak,*.pyc,*.class
set title                " change the terminal's title
set noerrorbells         " don't beep
