call pathogen#infect()
call pathogen#helptags()


filetype on  " Automatically detect file types.
set nocompatible  
syntax on

"let g:solarized_termcolors=256
set background=dark
colorscheme solarized




"autocmd BufRead,BufEnter,BufNewFile *.arc so /home/mds/projects/arc/arc2/vimarc.vim

filetype plugin indent on


let mapleader = ","
let g:mapleader = ","

set expandtab
set tabstop=4
set shiftwidth=4
set cindent
set autoindent
set smarttab

 

" gvim specific
set mousehide  " Hide mouse after chars typed
set mouse=a  " Mouse in all modes


set guioptions-=m
set guioptions-=T

set guifont=Menlo\ Regular:h14"


set incsearch
set hlsearch
set ignorecase
set smartcase

" get rid of highlighted searches with ,/
nmap <silent> <leader>/ :nohlsearch<CR>   



map j gj
map k gk
map $ g$
map ^ g^

" Add recently accessed projects menu (project plugin)
" set viminfo^=!
 
set formatoptions=tcq1


" Visual
set showmatch  " Show matching brackets.
set mat=2      " .2 seconds

" Backups & Files
set backup                     " Enable creation of backup file.
set backupdir=~/tmp " Where backups will go.
set directory=~/tmp     " Where temporary files will go.



set history=1000         " remember more commands and search history
set undolevels=1000      " use many muchos levels of undo

set title                " change the terminal's title

set noerrorbells         " don't beep
set novisualbell





set wildmode=list:longest
set wildmenu                "enable ctrl-n and ctrl-p to scroll thru matches
set wildignore=*.o,*.obj,*~ "stuff to ignore when tab completing
set wildignore+=*vim/backups*
set wildignore+=*sass-cache*
set wildignore+=*DS_Store*
set wildignore+=vendor/rails/**
set wildignore+=vendor/cache/**
set wildignore+=*.gem
set wildignore+=log/**
set wildignore+=tmp/**
set wildignore+=*.png,*.jpg,*.gif
set wildignore=*.swp,*.bak,*.pyc,*.class


set scrolloff=4         
set sidescrolloff=15
set sidescroll=1
